app = "santacruzservice"
primary_region = "cdg"

[build]
  builder = "heroku/builder:22"

[env]
  PORT = "3000"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/api/admin/healthcheck"
  timeout = "5s"
  protocol = "http" 